### ISSUE TITLE
HiDpi Extension Icon

### ISSUE THREAD

**Issue by panpipe** [svenackermann/Prime-Player-Google-Play-Music#115]
Hi,

First of all, fantastic extension! I use it every day and it's better than every alternative I've seen. Thanks for making it.

I use a Macbook Retina and because the icons are not HiDpi they appear blurry, which is not ideal. Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/777937/6202053/eddd9824-b4c8-11e4-82f1-64fa21b179f4.png)

The pop-up and miniplayer also have non-HiDpi images:
![image](https://cloud.githubusercontent.com/assets/777937/6202059/24cab2d6-b4c9-11e4-8051-5b5622d1efbd.png)

If I can help with this issue, I'd love to, I'm a graphic designer - sadly I don't know how to make a pull request or anything with the relevant files, but I can certainly help with the actual icons.

Thanks again!

**Comment by svenackermann** [comment]
Hi,

thank you very much for pointing that out. I'm just a develop, not a designer, so that sounds like you can really help me. That would be great.
You can find all the icons I use in Prime Player here: https://github.com/svenackermann/Prime-Player-Google-Play-Music/tree/develop/src/img
Most of them are from https://www.iconfinder.com/ or similar sites and some are from the Google Music site (just in case you search for a hi-res version of an image). I think for most of the icons you should recognize where they are used in the extension. If you're unsure, just ask me.

### Testing your changes
If you want replace an icon and then test if it looks good in the extension, I suggest the following:
First, deactivate Prime Player on the extensions page of Chrome (right-click the Prime Player icon, select "manage extensions" and then uncheck the "active" checkbox) as we are going to use a developer version for testing (you would get problems if you have 2 versions of Prime Player installed).
Download the latest version of Prime Player as zipped extension from [here](https://github.com/svenackermann/Prime-Player-Google-Play-Music/releases/download/2.28/PrimePlayer.zip). Unpack it anywhere on your PC and then go back to the Extension page in Chrome. Activate "developer mode" at the top right. At the top of the page you now have a button "load unpacked extension". Click it and select the folder where you unpacked Prime Player (the folder that contains the manifest.json file). Now you have the unpacked version installed. You can replace images in there (subfolder "img"), reload the extension (there's a link for that on the extensions page in the Prime Player section) and see what your change looks like. Make sure Prime Player is not connected to Google Music before reloading (either close Google Music or click the "P"-icon in the Google Music tab at the top left)
You can deactivate the unpacked version and re-activate the real version at any time (you can also install/uninstall it but that takes more time and you lose your settings then), but again make sure Prime Player is not connected to Google Music while doing so.

### Some things I want to point out
First, feel free to replace icons with a different one. It does not have to be exactly the same icon, so if you find a better one - no problem. They just should not be too fancy and tell the user what will happen when he clicks them. Of course, the icon should not be completely different as this might confuse existing users of the extension.

If you need to change the resolution of an image, that might need a change in Javascript or CSS code to make the image fit in the UI again. If you experience problems with this, I can provide a modified version of the extension that can handle the new resolution, so just ask me.

This is especially true for the file "sprites.png". This is basically a collection of some icons, each 30x30px in size. Please note the transparency in that image, you won't see everything with a white background. The icons in that file are organized in columns, each providing different states of an icon. E.g., the first column has the "thumbs up" icon in states "unrated", "unrated hovered", "rated" and "rated hovered" ("hovered" means that the mouse is hovered over the icon).
When on of these icons is used in the extension, the relevant part is virtually "cut out" and scaled to fit in the UI. This might sound complicated, but it is quite a standard way of using icon sprites.

A note on the browser icon: The images for this are contained in subfolder img/icon. There are some more subfolders for the different icon styles you can choose in the options. And there are some images for the overlays you can activate in the options (loved state, playing state, ...). These are dynamically painted over on runtime with some Javascript. The size of the browser icon is determined by Chrome to 19x19px. I just found out that I can also provide a 38x38px version, so you can scale that up, but this would need some changes in code by me. Just tell me, if you need sth.

The subfolder img/cmd contains images used in the buttons of toast notifications and in the browser icon (if the option "Show action symbol in icon" is enabled). I don't know if the size for notification button icons is determined to 30x30px, there's nothing mentioned in the documentation for Chrome notifications. If you change the size of these icons, they should be scaled down correctly to fit in the browser icon (19x19px at the moment, I would have to try if 38x38px works, too).

One last thing: Please have a look at the file size of the images. I don't want the extension size to become too big. Of course, the images should have good quality, but some compression should be fine.

I hope that you are still interested in helping me after I bombed you with that much information.

Thanks in advance,
Sven

**Comment by panpipe** [comment]
Thanks Sven, great of you to put the effort in to improve this!

I'll start small by changing just the browser icon and see how that works out. If that goes well then I can try and help with the UI as well.

Thanks,
Leo

**Comment by panpipe** [comment]
Well I tried to replace the browser icon but like you said, it needs some javascript from you to get it working. I did end up creating all the assets for the browser icon though - I've zipped them here:
http://cl.ly/1h393T0s3D0x

They are compressed - hopefully it doesn't add too much bulk to the extension.

I can see that the logo will work, as when I refresh the extension it briefly flashes up as the HiDpi version when I changed the manifest.json to this:

    "default_icon": {
      "19":"img/icon/default/notconnected.png",
      "38":"img/icon/default/notconnected2x.png"
    }

Let me know what you think so far - and I'll see what I can do about the UI elements later.

**Comment by svenackermann** [comment]
Great!
I created a modified version for you that handles the 38x38 images correctly: https://github.com/svenackermann/Prime-Player-Google-Play-Music/releases/download/3.0a/PrimePlayer-hires.zip

The overlay icons are now quite small, maybe you can make them 1-2px bigger again. And the paused overlay does not look very good in the icon. I guess this is because of the dynamic painting in Javascript.

Note that I just replaced the existing images, so no more 19x19px images exist now (according to Chrome's doc they should be correctly scaled down to fit in the browser bar).

Keep up the good work!

**Comment by panpipe** [comment]
Hi Sven,

It looks great for me now. 

![screen shot 2015-02-17 at 11 37 45](https://cloud.githubusercontent.com/assets/777937/6227598/dd66bac0-b699-11e4-8e34-92f3b3a60830.png)

Can I see a screenshot from you, so that I can see the downscaling that Chrome is doing? I think that might be the problem if the pause overlay looks bad. It might be that the only solution for the icons is to keep 19px versions.

**Comment by svenackermann** [comment]
No problem:
![image](https://cloud.githubusercontent.com/assets/2846807/6228984/7c9ec430-b6b2-11e4-95ba-4bb2996f018d.png)
As you can see, the "paused" overlay is kinda cut off at the right. Maybe it helps if you just make it 1px bolder.
I really would like to avoid keeping the 19px versions, because it makes things more complicated, but I guess you're right that we need both versions to get the best results.
I'm also not totally sure how to decide which size to choose, but I guess this is the "window.devicePixelRatio" property (see [here](http://www.quirksmode.org/blog/archives/2012/06/devicepixelrati.html)) which is "1" (->19px available) on my machine and should be "2" (->38px available) on yours. Can you test that (just open the developer console on any Chrome tab with F12, choose the console tab and type "window.devicePixelRatio" + Return)?

**Comment by panpipe** [comment]
Just tested and yes, it returns a 2.

Well I can try tweaking the pause image - if it works then maybe you can avoid having to use 2 sets of icons. I also wanted to nudge the last.fm heart icon down a bit - so it's symmetrical with the scrobbled icon.

**Comment by panpipe** [comment]
Here is the edited 'loved' and 'paused' logos. I made the paused logo a pixel wider for each stem, hopefully it works but I have a funny feeling chrome will make one fatter than the other.
http://cl.ly/2F1F1G251N19

**Comment by svenackermann** [comment]
It really looks better now. Here are two possiblities:
This is when I paint all the images on a 19x19px canvas, so scale-down is done in my Javascript code at composition time and Chrome gets already a 19x19px size icon:
![image](https://cloud.githubusercontent.com/assets/2846807/6243350/bfed74d8-b73f-11e4-98c8-fc1fd90d5670.png)
This is when I just paint it on a 38x38px canvas without scaling, so Chrome does the scale-down before showing the icon in the browser bar:
![image](https://cloud.githubusercontent.com/assets/2846807/6243409/c2290414-b740-11e4-8caa-4ee74da4f107.png)

The 2nd version looks totally ok to me and it also needs less code (since I do not have to do the scaling), so I would like to go this way.

Thanks again for the good work.

I did some bigger changes in the extension recently and plan to release that as version 3.0 (just to get rid of the 2.x). The new icons and an improved design would perfectly fit in that plan, so I'm really glad to have your support. Spending you a beer might be a bit hard since I guess you're not living in Germany, but if you like to support me with the other icons (or maybe other general design issues) I could include a 2nd donate or flattr button for you (you won't get rich with this, but it pays some small online orders).
For this new release I use a new feature in Chrome which unfortunately has a bug at the moment. So I'm waiting for a fix in Chrome before I can release the new version, which means that your improvements will also have to wait. I'm not sure how long it will take to be fixed (and to get the fix to the stable Chrome version), but someones already working on it and I guess I will wait at least 1 month, so you have a lot of time for improvements. Of course, if the fix in Chrome takes too long, I will release earlier without the new feature.

**Comment by panpipe** [comment]
I agree the second version looks fine and possibly a little sharper.

No worries from me on the delay - that's fine by me, I can continue using my Dev version, heh. Thanks, I appreciate that - I'll have to do enough to justify that first.

I'll start tinkering with the mini/pop-up player graphics today I think.

**Comment by svenackermann** [comment]
Hi,
I just updated some things and created a new dev version for you:
https://github.com/svenackermann/Prime-Player-Google-Play-Music/releases/download/3.0b/PrimePlayer.zip

This includes some new features compared to your version. Most interesting for you is that I had to add some new icons to the sprites.png file. They are used for the new favorites feature.

**Comment by panpipe** [comment]
Hi Sven,

I've got some questions about the sprite file. First of all, can we make a larger file, with bigger dimensions? At the moment I estimate the icons are ≥ 30px, on my computer in the 'normal' miniplayer they appear at around 50px and get scaled down a little for the compact miniplayers.

![image](https://cloud.githubusercontent.com/assets/777937/6433321/92316c70-c063-11e4-86cb-bfa292841de6.png)

How does the scaling work? I'm assuming if I upped the resolution of the icons in the sprite file, they would need to be scaled back down to fit in to the non-HiDpi layout again - similar to the icons on the right side of the player.

Sorry if this is a lot of work, if it's too complicated I can always try and work within the constraints of the current sprite file.

**Comment by svenackermann** [comment]
Hi,
the sprite consists of icons in size 30x30px. When one of the icons is needed somewhere, it is cut out and scaled down. The target size depends on where the icon is used, e.g the play controls have size 30px (not scaled) in standard layout and 20px in the other layouts, the buttons at the right (quicklinks, lastfm, ...) have 15px in standard layout and 13px in other layouts.
If you want to change to resolution of the sprites file, just do it. This should work just fine, the icons will always be scaled down to the needed size. Btw, this scaling is standard CSS, I don't use Javascript for that, normally this kind of scaling looks quite good.

To be more exact (and technical): when scaling to n px is needed, the whole sprite file is scaled to n*5 px height (*5 because the sprite is 5 icons high, width is scaled automatically to keep the original aspect ratio) and then it is moved left and up until the needed icon is in the top left corner. The icon then is put as background image in an HTML element of size n x n px. Sounds complicated but actually that is standard. Example: play icon for mouse hover (column 4, row 2 in sprite) needed in 20px - scale sprite to 100px height (1.5:1 ratio), move left 60px, move up 20px, put in 20x20px element.

Let me know if you have more questions or experience any problems.

**Comment by panpipe** [comment]
Ok, so I'll make a new sprite sheet with 60px icons. Might take a day or two. I don't know where to change the CSS for this stuff, so I guess I'll leave that to you.

**Comment by svenackermann** [comment]
Great! Take your time. As I said, there should be no need to change any Javascript or CSS code, the image should always scale to the desired size.

**Comment by panpipe** [comment]
Hey Sven,

It's been a while! Sorry about that.

Here is the updated Sprites file! http://cl.ly/3k1x1I3Y2C29

Works on my dev version of Prime (I only just understood your explanation of how the scaling is done). Look's good:
![screen shot 2015-04-11 at 18 22 49](https://cloud.githubusercontent.com/assets/777937/7102401/de57bd50-e077-11e4-8f6f-e48e9cadcb49.png)

I have slight reservations that the 'Feeling Lucky' symbol will not look great at small sizes. I can change it to 3 dots again if necessary.

I have noticed something odd with the star icon - it is always darker than the other symbols when highlighted - I assume it has some bonus CSS that the other symbols don't have. 

Let me know your thoughts!

**Comment by svenackermann** [comment]
Hi,

thanks a lot, everything looks great.

The 5-dots icon for "feeling lucky" doesn't look that bad for my resolution, but actually I think it should match the icon from the Google Music site which has 3 dots and no square around them. Otherwise users might be confused what the button is good for. You can find the original icon in the [sprites file](https://ssl.gstatic.com/play/music/fe/d57e7d6f6d6033dcb61e8cd427abc69a/sprites.png) of Google Music at position 626px/26px. The sprites file also contains some five-dots icons, but I don't know where/if they are used on the site. So if you don't mind, could you please change it back to a 3-dots icon?

There was actually an error in the CSS that caused the star icon to look darker. I corrected that, you can get the latest version [here](https://github.com/svenackermann/Prime-Player-Google-Play-Music/releases/download/3.0d/PrimePlayer.zip).

Thanks again for the great work.

**Comment by panpipe** [comment]
Okay, updated. Also changed the star symbol as I felt I'd made it a little too big.

Sprites: http://cl.ly/0Y3I143C2e3r

![screen shot 2015-04-13 at 17 49 58](https://cloud.githubusercontent.com/assets/777937/7120818/f16fd60c-e207-11e4-9d03-76f6563e0e62.png)

I guess the next thing to do is update the rest of the images in the /img/ folder? If I do that we should probably come up with a better way of sharing files. Do you use Dropbox? If not, I guess I could use my web server or something.

**Comment by svenackermann** [comment]
Hi,
the best way to share the files would be GitHub itself. Then we would have file histories and I could just get them to the real code with one click. But that would mean you'd have to learn some Git, I guess that'll be too much if you don't have any experience with revision control systems.

I do not use dropbox, but Google Drive. We could use a shared folder there (my mail address for granting access is svenrecknagel@gmail.com).
Of course we could paste the images directly here in the comments, but this only allows images, no zips. I think that's not a good idea, also for keeping the overview.

**Comment by svenackermann** [comment]
Hi again,
here are some infos on the remaining images. This should help you to know where to find the files in the application and which files you might give a higher resolution.

The table lists the images directly in folder "img". The column "fixed" means if the the size is fixed, "yes" means the resolution cannot be changed. The column "scaled" tells you if the icon would be automatically scaled (by CSS or Javascript) if you would change its resolution, "no" means I would have to change CSS or Javascript code to handle the higher resolution.

filename | fixed | scaled | where used
----------- | ----------- | ----------- | -----------
check | no | no | options page (last.fm connect success)
cover | yes* | no* | miniplayer / toast album cover (*: scaled & not fixed for miniplayer, but toasts use the file as is, maybe we could make 2 separate images)
cross | no | no | options page (last.fm connect error)
hint | no | no | options page (hints)
icon-128x128 | yes | no | extension icon, used by Chrome / Web store
icon-16x16 | yes | no | extension icon, used by Chrome / Web store
icon-48x48 | yes | no | extension icon, used by Chrome / Web store, also used as icon for notifications (timer & last.fm session timeout)
icon-alpha | no | no | notifications (alpha channel is used as icon in bottom right corner)
icon-tabconnected | no | no | Google Music site (replaces Googles headphones icon to mark the site as connected to Prime Player)
link-* | no | no | options page (social links)
paused | no | yes | miniplayer (indicator for current song if paused)
rating | no | no | toasts (parts are cut out to paint the rating on top of the album cover)
reload | no | no | Google Music site (lyrics reload icon)
sort | no | yes | miniplayer / options page (drag&drop sort marker for favorites / lyrics providers)
star-* | no | yes | miniplayer (star rating icon)

The "icon-alpha" image is not yet included in the last zipped version I gave you. If you really want to change it, I can provide a new version to you, but I think that file can be left as is.

The images in folder "cmd" are used for the toast buttons. They are displayed in their original size, so changing the resolution would make them appear bigger/smaller in toasts (so you can change the resolution but ensure that the toast buttons still look fine, Chrome does not say anything about a minimum/maximum size for that icons). The icon "openLyrics.png" is also used in the Google Music tab as button to open the lyrics.

**Comment by panpipe** [comment]
Hi Sven,

I'm willing to learn GitHub at some point - so I'll try and get around to that. For now I've just shared a folder with you on Google Drive.

Thanks for the table, it was helpful. Here are some notes about what I've done:

*check.png, cross.png, hint.png*
Updated to 32px - will need CSS changes (50% size)

*cover.png*
Ignored, already 100px, looks fine

*icon-128x128.png, etc.*
Ignored, already correct sizes

*link-github.png, link-... etc...*
Updated to 40px - will need CSS changes (50% size)

*paused.png, playing.gif*
Ignored, already look fine

*rating.png*
Updated to 32px icons - will need CSS/Java changes (50% size)
If scaling isn't possible for these toast icons let me know and I can make a smaller version again

*reload.png*
Updated to 32px

*sort.png*
Ignored, looks fine

*star-active.png, star... etc...*
Updated to 32px

-----------------------------

As for the 'cmd' folder, I tried using 60px icons and it made no difference to the size of them on the toast. The current ones look like this at the moment, which I think is fine, maybe I could update some of the symbols that aren't quite up to par.

![screen shot 2015-04-22 at 17 06 10](https://cloud.githubusercontent.com/assets/777937/7279803/79339a00-e916-11e4-842d-3a86fa4cd0b6.png)

**Comment by svenackermann** [comment]
Hi, thanks a lot.

[Here](https://github.com/svenackermann/Prime-Player-Google-Play-Music/releases/download/3.0e/PrimePlayer.zip) is the newest version. I updated all CSS/Javascript as needed (hopefully). I took all the images as is, only for the 'rating.png' I painted a white background. As these icons are painted on the album cover (I do not know how the album cover looks) they need a background to make sure they can be recognized for each cover (e.g. on an orange cover you won't see the thumbs up icon).

I guess that's it for now, no images left. Of course, if you like to improve the 'cmd' icons (or the 'icon-*' images), you're welcome. I would come up to you again when I need new images for new features, if you don't mind.

Thanks again for the good work.

I think I will release version 3.0 soon. I'm still waiting for a fix in Chrome, but I guess that will take some time and I don't want to wait much longer.

**Comment by panpipe** [comment]
Hey Sven,

No worries! I've enjoyed it. Let me know when you need any help.

Couple of issues, I've got a slight problem with that new icon-alpha image:
![screen shot 2015-04-23 at 13 19 40](https://cloud.githubusercontent.com/assets/777937/7296895/b233a318-e9bb-11e4-9fa6-07867e146afc.png)


Also, the 'rating.png' white background looks a little pixellated, so I've made a new version and put it in the google drive.

**Comment by svenackermann** [comment]
Hey, you're on a Mac, right? I guess the problem with the icon-alpha image is related to the Chrome version for Mac, it looks fine on my Windows PC (only the alpha channel is displayed and it is in the bottom right corner, i.e. in the 2nd button).
I will remove that icon again. If you give me your Chrome and Mac version, I can report an issue to Chrome for this (please go to https://code.google.com/p/chromium/issues/list, click "new issue" and just copy the version values from there).
Would you mind to check if this so called "app icon mask" looks bad fo other extensions, too. You could e.g. install [Checker Plus for Google Calendar](https://chrome.google.com/webstore/detail/checker-plus-for-google-c/hkhggnncdpfibdhinjiegagmopldibha), go to its options page, enable desktop notifications and click on the "Test it out!" link next to "Rich notification". This should have a small grey calendar icon in the bottom right corner:
![image](https://cloud.githubusercontent.com/assets/2846807/7313101/766aca6e-ea56-11e4-9ea1-af052b32884e.png)
The original image used for that icon is this:
![notificationminiicon](https://cloud.githubusercontent.com/assets/2846807/7313052/f68cc4d2-ea55-11e4-80e3-76fcd3cfb4ff.png)
If it looks good on your machine, maybe you get the point what is wrong with my image. Chrome docs say about that icon:
> The app icon mask should be in alpha channel, as only the alpha channel of the image will be considered.

I took your new version of the rating image with white background. Looks fine.

**Comment by panpipe** [comment]
Yeah, it could well be a Chrome for Mac bug. 

Here are my versions:
Chrome Version: 43.0.2357.18
Mac Version: OS X 10.10.3

I think I'm on the beta channel.

I tried out that Checker Plus extension. That icon does not show at all on the rich notifications - perhaps the developer has disabled it on the mac?

![screen shot 2015-04-24 at 16 45 39](https://cloud.githubusercontent.com/assets/777937/7322674/84b92e94-eaa1-11e4-8110-bf12591ebb77.png)

**Comment by svenackermann** [comment]
Yes, you're right. Checker Plus shows the icon only on Windows.
I'll file an issue to Chrome, maybe in a year it might be fixed and on the stable channel then ;-)

**Comment by panpipe** [comment]
Of course Google Play Music would come up with a redesign now. Of course they would.

**Comment by svenackermann** [comment]
Hi,

Google just marked the [issue](https://code.google.com/p/chromium/issues/detail?id=481448) about the alpha icon as fixed (it seems like it's already fixed since May 2015). I'm not sure if the current stable Chrome version includes that fix.

Could you do me a favor and check that for me on your Mac?

[Here](https://github.com/svenackermann/Prime-Player-Google-Play-Music/releases/download/3.8-appIconMask/PrimePlayer.zip) is a test version that is exactly version 3.8, but with that icon enabled again.
You can install this as unpacked extension like described earlier. For testing, any notification (toast or timer) will be fine. If it looks good (or not), please let me know.

Thanks in advance,
Sven

**Comment by svenackermann** [comment]
Hi @panpipe ,
did you see my last comment?
Thanks for looking into it,
Sven

**Comment by panpipe** [comment]
<img width="368" alt="screen shot 2016-03-16 at 12 47 59" src="https://cloud.githubusercontent.com/assets/777937/13812670/6b754b90-eb75-11e5-8c2a-751a51731716.png">

Hey, sorry missed your first comment. I just tested it, seems like it's fixed!

**Comment by svenackermann** [comment]
Thanks a lot, I will then include that in the next release.
