### ISSUE TITLE
After upgrade to 3.0, music stop playing next track

### ISSUE THREAD

**Issue by Gimli62** [svenackermann/Prime-Player-Google-Play-Music#127]
Support,

    Not sure if it is a defect or a new feature, but after upgrade to version 3.0 "Prime Player" prevent 'Google Play Music' to automatically play the next song when the previous one is finished.

    In situation where I've 'n' songs.
    Start Google Play Music (GPM) in Chrome Browser
    Start play song 'x'
    when song 'x' is finish, GPM automatically start to play song 'x+1'
    Launch Prime Player
    When song 'x+1' is completed, both  GPM and Prime Player switch to 'x+2' but song is paused
    I have to manually request to play the song for it to start.

Seems there is either an hidden setting preventing to smoothly play teh next song automatically, or there is a defect somewhere. (please note that this behavior didn't exist in previous version installed on my Chrome - extension).

Thanks
Gimli62

**Comment by svenackermann** [comment]
Sorry, I somehow missed that report. I'll look at this as soon as I'm back, currently on vacation.
This should not happen, there is nothing like an "auto-pause" feature.

**Comment by svenackermann** [comment]
Hi again. I cannot reproduce your problem. Does this still happen with the latest version?

I looked in the code, there is only one possibility that Prime Player automatically pauses music without user interaction. There is an option to pause music when your computer is gets idle or locked. You can check that. If this is not the cause, please try to give me some more details.
Of course, you should always first try to restart Chrome, reload Google Music and also check if the problem still happens when you disable/uninstall Prime Player.

**Comment by svenackermann** [comment]
closed because no reaction in almost 2 months
