### ISSUE TITLE
Idea for bringing 5-star ratings back

### ISSUE THREAD

**Issue by mikemelton** [svenackermann/Prime-Player-Google-Play-Music#136]
Google removing 5-star ratings destroyed me. Glancing at message boards around the internet, it's clear I'm not the only one. I was lucky, though; I never shut down my laptop and so when I noticed the new design and lack of star ratings on my desktop computer, I quickly used my laptop (whose GPM tab hadn't been reloaded) to create playlists for each rating tier. Now I have playlists for Unrated, 1 Star, 2 Star, 3 Star, etc. Obviously this is a huge maintenance burden but I realize I'm lucky to have been able to save my thousands of ratings in some way.

This got me thinking, though; now I have all the information that Prime Player needs to decide what a song's 5-star rating is. I've given it some thought, and here are some high-level design ideas:

* Standardize the names of star rating playlists; maybe `1-star`, `2-star`, etc.
* Given that GPM only allows 1000 songs in a user-created playlist (wtf?), we have to allow for indexing as well to accommodate star ratings with more than 1000 songs. Probably something simple like `4-star-0`, `4-star-1`, etc.
* When a song is playing, check for its existence in one of these standard playlists. If it exists, show the corresponding star rating.
* When rating a song, check if it exists in the corresponding playlist. If not, add it (creating a new indexed playlist for that rating if we've reached the 1000 song limit). When changing a rating (as opposed to creating a new rating), remove the song from the old rating's playlist.
* To pass ratings on to Google, I guess we can stick to Google's asinine scheme where 4 or 5 stars = thumbs up, 1 or 2 stars = thumbs down. I hate it, but can't come up with anything better.

I realize GPM doesn't have an API and I haven't dug into Prime Player's code other than a quick glance, so I have no idea if what I'm proposing is even possible. I'm a developer and would like to spend some time working on this, but I thought I'd ping you first to determine feasibility. Thoughts?

**Comment by svenackermann** [comment]
Hi, thanks for your ideas.
I also hate it that the stars-lab has been removed, but what you suggest is
 1. technically almost impossible and
 2. too complicated/confusing for most users.

At the moment, Prime Player has no possibility to manipulate playlists, it's easy to show them, but that's it. All that Prime Player does is done on the web page of Play Music, so when I show a playlist in the miniplayer, I first must open it on the page and parse its contents. Adding songs to a list would require the song to be playing, then I would have to simulate a click on the "3-dots" next to the thumbs to open the context menu, select the right entry and click it. That is quite hard to do and extremely error-prone. Removing a song from a list is only possible while the list is shown, there's no entry for that in the normal context menu at the bottom, only in the context menu in the playlist. Creating/Removing the playlists would require almost the same steps, but in the playlists area in the left panel. But in fact that is the easier part. The hardest would be to read all the playlists and check for existence of a song in there. For this I would have to open all playlists one by one, parse them and find the song (this takes some seconds). Whenever a new song starts I would have to this. Of course, I could do this only once when the Google page is opened the first time and remember all the playlists. But this would still require some extra time at startup and introduce the possibility of getting out of sync.

The good news is that the star-ratings are still there, you can see them in all song-tables (like playlists, albums, queue, ...). If you inspect the column at the right (where the thumbs are), you'll see that it is sth. like a

    <td data-col="rating" data-rating="4">

The `data-rating` attribute shows your rating (from 1-5 or 0 if unrated). I could easily read this, but unfortunately there's no possibility to change the rating to sth. different than 0, 1 or 5, because I only have the thumbs to click on. Also, it's not possible to get the rating for the current song from the thumbs in the player area at the bottom, because the `data-rating` attribute is missing there. I played a bit around and was even possible to manipulate the markup so that it's possible to rate a song to 2/3/4 from a song table as well as from the player at the bottom, but the blocker is still that I can't get the rating for the current song (I could maybe try to get it from the queue instead of the player area, but this still has some challenges because the queue does not always display the current song, so I would have to scroll there).

Conclusion: Your suggestion is too hard/almost impossible to realize, my suggestion is still hard to realize and a bit error-prone, but not impossible. Since Google might completely remove the star ratings (i.e. the `data-rating` attribute) in the (near) future or even bring the stars lab back, I don't think that it makes sense to implement this.

**Comment by svenackermann** [comment]
OK, after some more experiments I decided to give my suggestion a try, but that will definitely be an experimental feature.

**Comment by mikemelton** [comment]
Awesome! Thanks, Sven - I look forward to it. If you need help testing, I use Prime Player pretty much all day everyday :)

**Comment by rubin110** [comment]
svenackermann: You are awesome! This is great! I'm almost in tears.
