### ISSUE TITLE
Forgetting playlist and play state

### ISSUE THREAD

**Issue by rubin110** [svenackermann/Prime-Player-Google-Play-Music#139]
Prime Player 3.2.1
Chrome Unstable 45.0.2438.3 dev (64-bit)

When the Prime Player plugin is enabled, if I refresh the Google Music tab or restart my browser and have my tabs reload, Google Music forgets what was in my playlist, what item in my play list I was listening to last, and what the players state was (playing or paused).

If I disable Prime Player, the tab on reload is able to pick up where it left off.

**Comment by svenackermann** [comment]
Hi, sorry but I cannot reproduce this. It is completetly new to me that Google Music is able to remember your queue/playlist. When I reload GM or restart Chrome, everything is gone, no matter if PP is enabled or not. I tried this many times, but no difference. Can you provide more details what you are doing? Do you have some other extension or lab or whatever?

**Comment by rubin110** [comment]
The only other extension of relevance here would be Google Play Music 1.275.2. Labs are gone from Google Music so there's none of that.

Futsing with this more. I can get repro in my main Chrome session on unstable/dev is inconsistent. It works 100% of the time without Prime Player, and fails about half the time when the extension is enabled.

Testing this out on Chrome Stable Version 43.0.2357.130 (64-bit), my repro steps where...

1. Install Chrome.
2. Start a fresh browser session with no user data.
3. Log into Chrome with my Google account.
4. Install the Google Play Music extension/app.
5. Log into Google Play Music.
6. Restart Chrome.
7. Go to Google Play Music.
8. Start playing a song.
9. Refresh tab.
10. Observe.
11. Install Prime Player.
12. Restart Chrome.
13. Go to Google Play Music.
14. Start playing a song.
15. Refresh tab.
16. Observe.

Expected results:
Tab reload and playlist and song time position is maintained.

Actual results:
Step 16, about half the time after reload the playlist is cleared out.

**Comment by svenackermann** [comment]
OK, the Google Play Music app seems to keep the playlist. But I still cannot repro your problem. Reloading the tab always keeps the list, no matter if PP is installed or not. I can even restart Chrome (when background apps are enabled) and the list is still there (assuming the tab is pinned).

Note the following: I have no control over Googles miniplayer, just the Google Music page. I observed that I can open the Google Music page while the Google miniplayer is open and playling music, then the Google page does not display the playing track. Because PP connects to the page rather than the miniplayer, it will also not recognize the playing track. Conclusion: Do not use Googles miniplayer together with PP, this thing is just out of my control.

It does matter how you open the Google Music page. If you open the page from Googles miniplayer you might get different results than if you open it from PPs miniplayer or from a bookmark. The Google app as well as PP might do dome extra magic after the Google page has been opened (e.g. to load a playlist or resume the last song).

But again: When I do your steps above (just reloading GM), the playlist is always kept for me.

**Comment by svenackermann** [comment]
closed for inactivity
