### ISSUE TITLE
Option to remove timeout?

### ISSUE THREAD

**Issue by cwilliams5** [svenackermann/Prime-Player-Google-Play-Music#165]
When I have a long day working Play Music eventually will just stop playing. It enters a pause state, merely clicking play will resume it. I haven't timed it exactly but its definitely many hours. I figure its a timeout similar to Pandora's "are you still listening" thing. If I'm not crazy and this is a real thing, it would be great if Prime Player could simulate some sort of user activity to extend this timeout indefinitely, the way my Pandora userscript does it.

Also, you may want to add this to your FAQ on keyboard controls: chrome cannot read keyboard inputs in a program that is running as administrator unless Chrome is also ran as administrator. I was frustrated by Prime Player shortcuts not working in Steam games, but then realized this was the cause.

Thanks for such an awesome extension!

**Comment by cwilliams5** [comment]
OK I'm not crazy - where it used to happen with no notification at all now I see a dialogue:

![Inactivity Dialogue](http://codywilliams.com/crap/inactivity.png)

Would be fantastic if prime player could detect this and hit resume playing.

**Comment by svenackermann** [comment]
Sorry that I didn't respond earlier. Not much time, you know christmas and stuff...

That would be a nice feature and I would like to add it. Unfortunately, this is kinda hard to test/reproduce since I would have to wait until the auto-pause-"feature" triggers. At the moment I really do not have time for this. But you can help me:
When the popup above comes up, right-click the "resume playing" button and select "inspect element" from the context menu (I don't know exactly how this action is called in English, it's the last one in the context menu). This will open the Chrome developer tools. You then can send me a screenshot of that. In particular the line at the bottom (starting with "html body ...") is interesting for me.

Also thanks for the hint regarding the shortcuts FAQ.

**Comment by cwilliams5** [comment]
No need to apologize. Me and all the other silent users of Prime Player thank you for every second you spend on this project.

I will get you the above info as soon as I can - but there has been a problem. As I mentioned in my first post, this dialogue doesn't always pop up. I think its a bug with Google Play Music. If I leave it running for a long period of time, it always eventually pauses the music. But only sometimes produces the dialog. I'd say its like only 10% of the time I get the dialog. I've been trying since your post with no luck yet.

Given this bug and the timeout prompt being unreliable, I was thinking a better solution was some way to simulate user behavior. I don't know if this will help, but while googling the issue I found this entry in another project:

https://bugs.launchpad.net/nuvola-player/+bug/913973

It describes the same problem, and says a fix was added to the program. Here is the revision with the fix:

https://bazaar.launchpad.net/~fenryxo/nuvola-player/1.1.x/revision/452

```javascript
var ACTIVITY_INTERVAL = 15*60*1000;

 if(Nuvola.config.simulateActivity === true){
setTimeout(Nuvola.bind(this, this.simulateActivity), ACTIVITY_INTERVAL);
}
  
Integration.prototype.simulateActivity = function(){
var elm = document.getElementById("insideBox");
if(elm){
console.log("Click on " + elm);
Nuvola.clickOnElement(elm);
setTimeout(Nuvola.bind(this, this.simulateActivity), ACTIVITY_INTERVAL);
}
}
```

I don't know Javascript super well, but that looks to me like that code might be of use :D Looks likes both projects are BSD so no code use issue.

Although it surprises me they use a set time. Seems easy for Google to detect. Adding a slight variance would probably be more resistant.

Actually on further inspection, and I'm not the best with Javascript, but I can't see that the element "insideBox" exists anymore on current Google Music. Maybe we can change the script to click somewhere else? Or perform a different action which Google Music will accept as user activity? I found the current branch of the above code (https://github.com/tiliado/nuvola-app-google-play-music/) but it doesn't appear to have the simulateActivity or similar code anymore.

**Comment by svenackermann** [comment]
Hi, thanks for your reply.
If the popup doesn't show up every time the music auto-pauses, it would definitely be the better solution to simulate user activity. I also thought about sth. like the code above, but actually as a Chrome extension I have better possibilities.
The only question left is what user action I should simulate. I don't know how the mechanism to detect inactivity works, so I cannot know which action suffices. I identified the following requirements for that action:

1. It must not break the playing music (like pause or fast forward).
2. It must not modify the user's data (like thumbs up/down).
3. It must be available on every page in Google Music, so likely it will be at the top or bottom bar or in the hamburger menu on the left.
4. Ideally the action is not visible to the user to avoid confusion about some magic action happening if he just looks at the page at that moment (or works on it). That's why I would avoid the hamburger menu.
5. It would be nice if it's some action that is already used in Prime Player, so I would not have to implement some new action.

Given all that, the best possible action for me would be to click the volume bar at its current position (or maybe change the volume by 10% for a second). I could do that just a second before the current song ends, so normally the volume change will not be recognized. I could also click the next button just before the current song ends. Do have any better ideas?

If you don't mind, I will then build some kind of beta version just for you to try it out. When you then say "it worked", I'll let it be part of the next release.

**Comment by cwilliams5** [comment]
I had a similar set of ideas in mind, especially volume control! The only potential problem is we don't know for sure what it will detect as user activity or not. But we will just have to test.

I think clicking the volume at its current level is a great idea - it would have zero impact to the user. If that doesn't work, we can move on to the next idea, volume adjustment or next button.

Also, we know there is no need to do this every song - just often enough to disable the pause. I've narrowed the pause down to 6 hours. So I would say once every 5 hours, but then I wounder why the Nuvola program above used 15 minutes. Do they know something we don't? We can do the 15 minutes as well or go for something like 1 hour. Whatever you would like to try.

Also, not that Google is detecting, but something that happens at exact timing would be easy to defeat. Either you can program in a random amount (instead of an hour, somewhere between 55-65 minutes for example) or use an existing variable (60 minutes + length of current song. Store a time behavior, check it at the beginning of every song. If its >60min at beginning of song, know to do simulate activity at end of that song and reset variable). The delay could be configurable, but I'm not sure if there is an actual benefit to that. You know better then I your existing options in Prime Player.

Thank you again for working on this, and everything in Prime Player! I will test anything you need me to!

**Comment by svenackermann** [comment]
Hi,

I now have created a test release [here](https://github.com/svenackermann/Prime-Player-Google-Play-Music/releases/tag/3.8a).

This is version 3.7.1 with a user activity simulation added. This will just click the volume bar once an hour at the end of a song. I don't think Google will detect this as some kind of bot. There is no option yet, it's just always enabled.

To install it:

1. download the PrimePlayer.zip from the page linked above & unpack it somewhere
2. close Google Music
3. Go to chrome://extensions
4. find & disable the Prime Player you downloaded from the Web Store
5. enable developer mode at the top
6. click "load unpacked extension" & choose the folder where you unpacked it

You then might need to reconfigure your options, they are not synchronized between the real and unpacked version. Everything else should be the same (except for the new feature). Chrome will show you an annoying warning about the unpacked extension each time you start Chrome, just ignore that (if you trust me). You can switch back to the real extension by just disabling (or removing) the unpacked version an re-enabling the downloaded version (you should close Google Music first).

**Comment by cwilliams5** [comment]
Just so you know I am testing. Had 2 long sessions, one it still paused and the other it lasted the whole time. But I have some evidence from an unrelated application that my internet may have cut out the first session. So testing for a few more days so I can give you a solid answer!

**Comment by cwilliams5** [comment]
Okay, this has been working perfectly all week! I'm convinced the one time it didn't must have been a network interruption causing a pause state. My 10 hour work days have been filled with music and no pauses. Thank you again for adding this feature! If you need any further testing just let me know, I'm subscribed here or can give you my email.
