### ISSUE TITLE
Issues with Musixmatch Lyrics - wrong lyrics or no lyrics while there are right lyrcs on the site Musixmatch.com also, wrong lyrics if there's no lyrics

### ISSUE THREAD

**Issue by dadapotok** [svenackermann/Prime-Player-Google-Play-Music#176]
_Please provide at least the following information:_
#### General information
- Chrome version:  Version 50.0.2661.86 (64-bit)
- Prime Player version: Version 3.11 (4/19/2016)
- operating system: Mac OS X 10.11.2 (15C50)
- country where you are using Prime Player: Russia
- labs enabled in Google Music (if any): no

#### Description
Issues with Musixmatch Lyrics

Please include affected components (e.g. miniplayer, popup, options page, toast, keyboard shortcuts, Google Music site).

Sometimes it works sometimes it's not.

Tested Artists and tracks with lyrics exists on musixmatch.com and no lyrics or wrong lyrics (another songs with another names somehow) in Prime Player lyrics box:
artist - album - song
Steve Jansen - Tender Extinction - Her Distance (feat. Perry Blake) shows Steve Jansen - Sow the Salt Lyrics, I don't have any clue why. Tested on the pure copy of Chrome also. Right lyrics [exists](https://www.musixmatch.com/lyrics/Steve-Jansen/Sow-the-Salt)
Lonesome Wyatt & Rachel Brooke - Bad Omen - "When You Are Young" shows  Lonesome Wyatt and Rachel Brooke - "Never Forget" instead.  Right lyrics [exists](https://www.musixmatch.com/lyrics/Lonesome-Wyatt-and-Rachel-Brooke/When-You-Are-Young)

Same issue on the all tracks from that albums. Other lyrics extensions also fails. Maybe there's something with the artists name handling?

## To get wrong lyrics  if there's right lyrics
1. try to listen and fetch [this](https://play.google.com/music/m/Tvlwwdpl3iufrpe7r6w6juk6ruq?t=Evil_One_-_Lonesome_Wyatt__Rachel_Brooke) 
2. Check the lyrics on the musixmatch [here](https://www.musixmatch.com/lyrics/Lonesome-Wyatt-and-Rachel-Brooke/Evil-One)

## To get wrong lyrics if there's no lyrics
1. try to listen and fetch [this](https://play.google.com/music/m/Trjr6dpeyzxt5ujshn7sobd6oye?t=Captured_feat_Thomas_Feiner_-_Steve_Jansen)

#### Expected behavior
1. Show right lyrics

2. Show no lyrics

#### Actual behavior
Shows wrong lyrics all the time

**Comment by svenackermann** [comment]
Hi,

many thanks for your report. Actually, I already found out that sth. is wrong with the musixmatch integration because of a change on their site. It's already fixed and will be included in the next version.

Your description is a bit confusing. I never get any lyrics from musixmatch, so I can't get "wrong lyrics". Note that Prime Player always just shows the first result on the site behind the "search result" link. So the result in Prime Player depends on what the search in musixmatch gives me. If there is no result on that page, Prime Player won't display any lyrics. If there is a result, Prime Player will try to load its page and get the lyrics from there. This is currently not working because of a small redesign of that page.

Please retest after the new version is released (I can't tell you when that will be) and reopen if needed.

Regards,
Sven
