### ISSUE TITLE
"Connecting to Google Music..." indefinitely

### ISSUE THREAD

**Issue by taylorhughes** [svenackermann/Prime-Player-Google-Play-Music#195]
_Please provide at least the following information:_
#### General information
- Chrome version: 53.0.2785.116
- Prime Player version: 4.2.2
- operating system: OS X 10.11.6
- country where you are using Prime Player: US
- labs enabled in Google Music (if any): none

#### Description

A few weeks ago Prime Player stopped working for me. The blue dots icon appears on the "P" and says "Connecting to Google Music..." and stays like that while music.google.com is open.

I work at Google so this could be related to unreleased changes, but I can also reproduce with the public version of Music on this machine, so I'm not sure what's going on here.

I'd love to help debug this, but I don't know where to start. Let me know if there are additional tests I can run to help figure this out. I miss the play/pause/next keyboard mappings. :)

**Comment by svenackermann** [comment]
Hi,
thanks for the report.
I just tested this and it works for me (Chrome 52.0.2743.116 m, at work I do not get the latest version). You're also the 1st user to report this, so I guess it's not a general problem.
But in fact when I let the Google Music tab open in background (and pinned in my case), Prime Player does not connect. It only connects once I activate the tab. There were always problems with the tab in the background and I already did a lot of workarounds to make this work, but it seems to be broken again (which is normally caused by an update on the Google Music site).
Unfortunately I have absolutely no time at the moment to debug/fix this. You can try to build a developer version of Prime Player (see [here](https://github.com/svenackermann/Prime-Player-Google-Play-Music/blob/develop/.github/CONTRIBUTING.md#setup)) which outputs some debug information to the console, maybe that helps. My experience is that Chrome from one version on started to restrict page loading and user interaction for a tab in background, so the page is just not fully loaded. To workaround this, I added the expert option "Make Google Music tab visible when needed" but that does not seem to work anymore in this case.

So as a workaround, try to disable the "open in background" option or just activate the tab for a second to connect.

When I have some time, I will try to fix this, but contributions are very welcome.

Best regards,
Sven

**Comment by taylorhughes** [comment]
It's resolved itself, it seems. Sorry for the noise, thanks for the great extension!
